# <host-port>:<container-port>

services:

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID:1000
      - PGID:1000
      - TZ=Europe/London
      - HOMEPAGE_ALLOWED_HOSTS=iqbal:3000,192.168.0.13:3000,100.98.125.7:3000
    ports:
      - 3000:3000
    volumes:
      - ./homepage/config:/app/config
      - ./homepage/media:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media-server:/mnt/storage:ro
    restart: always

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    network_mode: host
    volumes:
      - ./plex/config:/config
      - /media-server/data/media/tv:/tv
      - /media-server/data/media/movies:/movies
      - /media-server/data/media/music:/music
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_UID=1000
      - PLEX_GUID=1000
      - TZ=Europe/London
      - VERSION=docker
      - PLEX_CLAIM=claim-i7Mwm5AsKJLpzbmktxR7

  overseer:
    image: linuxserver/overseerr:latest
    container_name: overseer
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./overseerr/config:/config
    ports:
      - 5055:5055

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - ./sonarr/config:/config
      - /media-server/data:/data
    ports:
      - "8989:8989"

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - ./radarr/config:/config
      - /media-server/data:/data
    ports:
      - 7878:7878

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - ./lidarr/config:/config
      - /media-server/data:/data
    ports:
      - 8686:8686
    restart: always

  readarr:
    image: ghcr.io/pennydreadful/bookshelf:hardcover
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - ./readarr/data:/config
      - /media-server/data:/data
    ports:
      - 8787:8787
    restart: always

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./prowlarr/config:/config
    # depends_on:
    #   - nordlynx
    # network_mode: service:nordlynx
    ports:
      - 9696:9696

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    volumes:
      - ./flaresolverr/config:/app/config
    container_name: flaresolverr
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    # depends_on:
    #   - nordlynx
    # network_mode: service:nordlynx
    restart: always

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /media-server/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://192.168.0.13:8989
      - UN_SONARR_0_API_KEY=af9254e205bc44bd99a81e325d6a3ea4
      - UN_SONARR_0_PATHS_0=/data/torrents/tv-sonarr,/data/usenet/complete/tv
      - UN_SONARR_0_PROTOCOLS=torrent,usenet
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://192.168.0.13:7878
      - UN_RADARR_0_API_KEY=ec5b428b7ea04020bfa8df56024c79f8
      - UN_RADARR_0_PATHS_0=/data/torrents/radarr,/data/usenet/complete/movies
      - UN_RADARR_0_PROTOCOLS=torrent,usenet
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Lidarr Config
      - UN_LIDARR_0_URL=http://192.168.0.13:8686
      - UN_LIDARR_0_API_KEY=7c77e776e75c4f77b391ce011da1a7ff
      - UN_LIDARR_0_PATHS_0=/data/torrents/lidarr,/data/usenet/complete/music
      - UN_LIDARR_0_PROTOCOLS=torrent,usenet
      - UN_LIDARR_0_TIMEOUT=10s
      - UN_LIDARR_0_DELETE_ORIG=false
      - UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
      - UN_READARR_0_URL=http://192.168.0.13:8787
      - UN_READARR_0_API_KEY=a4b9c32a9ec94028bfb0adccadb432e4
      - UN_READARR_0_PATHS_0=/data/torrents/readarr,/data/usenet/complete/books
      - UN_READARR_0_PROTOCOLS=torrent,usenet
      - UN_READARR_0_TIMEOUT=10s
      - UN_READARR_0_DELETE_ORIG=false
      - UN_READARR_0_DELETE_DELAY=5m
    # secrets:
    #   - sonarr_api_key
    #   - radarr_api_key
    #   - lidarr_api_key
    #   - readarr_api_key
    security_opt:
      - no-new-privileges:true
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=1916
      - TORRENTING_PORT=6881
    ports:
      - 1916:1916
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/app/vuetorrent:/opt/vuetorrent/
      - ./qbittorrent/app/nightwalker:/opt/nightwalker/
      - /media-server/data/torrents:/data/torrents
    restart: always
    # depends_on:
    #   - nordlynx
    # network_mode: service:nordlynx

  SABnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    volumes:
      - ./sabnzbd:/config
      - /media-server/data/usenet:/data/usenet
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    ports:
      - 8088:8080
    restart: always

  nginx:
    container_name: nginx
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # - '21:21' # FTP
    environment:
      - TZ=Europe/London
      - DISABLE_IPV6=true
    volumes:
      - ./nginx:/data
      - ./letsencrypt:/etc/letsencrypt

  # nordlynx:
  #   container_name: nordlynx
  #   image: ghcr.io/bubuntux/nordlynx
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PRIVATE_KEY=+NARn8mufh70/9sThSD062U4VVzd/SYH7ErzKEj5tVk=
  #     - TZ=Europe/London
  #     - LOG_LEVEL=debug # Add this line to enable debug logging
  #     - NORDLYNX_DEBUG=1 # Add this line to enable NordLynx debug mode
  #     - CONNECT=United_Kingdom
  # secrets:
  #   - nord_private_key
  # hostname: nordlynx
  # ports:
  #   - 6881:6881
  #   - 6881:6881/udp
  #   - 1916:1916
  #   - 9696:9696
  #   - 8191:8191
  # sysctls:
  #   - net.ipv4.conf.all.src_valid_mark=1
  #   - net.ipv4.conf.all.rp_filter=2
  #   - net.ipv6.conf.all.disable_ipv6=1

  # nordvpn:
  #   image: ghcr.io/bubuntux/nordvpn
  #   container_name: nordpvn
  #   cap_add:
  #     - NET_ADMIN               # Required
  #     - NET_RAW                 # Required
  #   environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
  #     - TOKEN=e9f2abf3373b8e9dd3b476963844c239ff4df38aab2ff1f45a80c9c404ae0ff0     # Required
  #     - CONNECT=United_Kingdom
  #     - TECHNOLOGY=NordLynx
  #     - NETWORK=192.168.1.0/24  # So it can be accessed within the local network
  #   ports:
  #     - 8080:8080
  #   sysctls:
  #     - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./calibre:/config
      - /media-server/data/media/books:/books
    ports:
      - 8082:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./calibre-web:/config
      - ./calibre/:/calibre
      - /media-server/data/media/books:/books
    ports:
      - 8083:8083
    restart: always

  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: always
    ports:
      - "5454:5454"
    volumes:
      - ./notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      - DN_API_KEY=/run/secrets/notifiarr_api_key
      - TZ=Europe/London

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    environment:
      - TZ=Europe/London

secrets:
  sonarr_api_key:
    file: ./secrets/sonarr_api_key
  radarr_api_key:
    file: ./secrets/radarr_api_key
  lidarr_api_key:
    file: ./secrets/lidarr_api_key
  readarr_api_key:
    file: ./secrets/readarr_api_key
  notifiarr_api_key:
    file: ./secrets/notifiarr_key
  nord_private_key:
    file: ./secrets/nord_private_key
  postgres_password:
    file: ./secrets/postgres_password
  email:
    file: ./secrets/email_address
