---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Library:
      - Plex:
            icon: plex.png
            href: http://192.168.0.254:32400/web
            description: Media server
      - Navidrome:
            icon: navidrome.png
            href: http://192.168.0.254:4533
            description: Music server
      - Overseerr:
            icon: overseerr.png
            href: http://192.168.0.254:5055
            description: Request management and media discovery

- Request Management:
      - Lidarr:
            icon: lidarr.png
            href: http://192.168.0.254:8686
            description: Music request management
      - Readarr:
            icon: readarr.png
            href: http://192.168.0.254:8787
            description: Books request management
      - Sonarr:
            icon: sonarr.png
            href: http://192.168.0.254:8989
            description: TV management
      - Radarr:
            icon: radarr.png
            href: http://192.168.0.254:7878
            description: Movies Management

- Network Tools:
      - Nginx:
            icon: nginx.png
            href: http://192.168.0.254:80
            description: Reverse proxy
      - Adguardhome:
            icon: adguard-home.png
            href: http://192.168.0.254:3001
            description: Ad blocker
      - Cloudflare:
            icon: cloudflare.png
            href: http://192.168.0.254:8082
      - Portainer:
            icon: portainer.png
            href: http://192.168.0.254:9000

- Download:
      - qBitTorrent:
            icon: qbittorrent.png
            href: http://192.168.0.254:1916
            description: Torrent client
      - SABnzbd:
            icon: sabnzbd.png
            href: http://192.168.0.254:8088
            description: Usenet client
      - Prowlarr:
            icon: prowlarr.png
            href: http://192.168.0.254:9696
            description: Index handler

- Utility:
      - PGAdmin:
            icon: pgadmin.png
            href: http://192.168.0.254:8888
      - code-server:
            icon: code-server
            href: http://192.168.0.254:8443
            